version: "3.9"

services:
  
  # MariaDB
  db:
    container_name: db
    env_file: .env
    build: docker/MariaDB
    volumes:
      - ./docker/MariaDB/logs/mysqld.log:/var/log/mysql/mysqld.log
      - ./docker/MariaDB/logs/mysql-error.log:/var/log/mysql/mysql-error.log
      - ./docker/MariaDB/db:/var/lib/mysql
      - ./schema:/schema
    ports:
      - 3306:3306
      - 33060:33060

  # Node.js
  nodejs:
    container_name: nodejs
    env_file: .env
    build: ./docker/nodejs
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000

  #ドキュメントの校正
  redpen:
    container_name: redpen
    build: ./docker/redpen
    volumes:
      - .:/tmp