version: "3.9"

services:
  
  # MariaDB
  db:
    container_name: db
    env_file: .env
    build: docker/MariaDB
    volumes:
      - ./docker/MariaDB/logs/mysqld.log:/var/log/mysql/mysqld.log
      - ./docker/MariaDB/logs/mysql-error.log:/var/log/mysql/mysql-error.log
      - ./docker/MariaDB/db:/var/lib/mysql
      - ./schema:/schema
    ports:
      - 3306:3306
      - 33060:33060

  # Node.js
  nodejs:
    container_name: nodejs
    env_file: .env
    image: node:20.9.0
    links:
      - db
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
    command: >
      bash -c "npm install -g npm && npm install && npm run dev"

  #ドキュメントの校正
  redpen:
    container_name: redpen
    build: ./docker/redpen
    volumes:
      - .:/redpen
    profiles:
      - lint