name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  Test_CI:
    runs-on: ubuntu-latest
    steps:
      - name: reviewdogをインストール
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.11.0
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: nodejsの設定
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: nodeのインストール
        run: npm install
      - name: 対象ファイルを探し、textlintを実行
        run: bash .github/find_text.sh

  # Redpen
  # https://github.com/tsuyoshicho/action-redpen
  document_Redpen_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Redpenを実行
        uses: tsuyoshicho/action-redpen@v1.4.2
        with:
          reporter: github-pr-review
          targets: "*.md"
          config: docs/config/Redpen-config.xml

  # Textlint
  # URL: https://github.com/tsuyoshicho/action-textlint
  document_textlint_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: nodejsの設定
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: nodeのインストール
        run: npm install
      - name: textlintの実行
        uses: tsuyoshicho/action-textlint@v3.0.1
        with:
          reporter: github-pr-review
          level: error
          textlint_flags: '. --ext .md'

  # Alex
  # https://github.com/reviewdog/action-alex
  alex_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: alexによる査読
        uses: reviewdog/action-alex@v1.2.0
        with:
          reporter: github-pr-review
          level: warning
          alex_flags: '. --ext .md'