name: CI

on:
  pull_request:
    branches: 
      - develop
      - main

jobs:
  document_Redpen_CI:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: javaをダウンロードしてくる
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: 'jre'
          architecture: x64
      - name: ダウンローダ、解答ソフトをインストール
        run: sudo apt-get install -y wget tar
      - name: EULAに合意する
        run: sudo ACCEPT_EULA=Y
      - name: Redpenのインストール
        env:
          Redpen_ver: 1.10.4
        run: |
          wget https://github.com/redpen-cc/redpen/releases/download/redpen-${Redpen_ver}/redpen-${Redpen_ver}.tar.gz
          tar xvf redpen-${Redpen_ver}.tar.gz
          sudo cp -av redpen-distribution-${Redpen_ver}/* /usr/local/
          rm -rf redpen-distribution-${Redpen_ver}
      - name: pathに追加
        run: export PATH=$PATH:/usr/local/bin
      - name: Redpenの実行
        run: sh docker/redpen/docker-entrypoint.sh
