name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Redpen
  # https://github.com/tsuyoshicho/action-redpen
  document_Redpen_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Redpenを実行
        uses: tsuyoshicho/action-redpen@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          reporter: github-pr-review
          targets: "*.md"
          config: docs/config/Redpen-config.xml

  # Textlint
  # URL: https://github.com/tsuyoshicho/action-textlint
  document_textlint_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: nodejsの設定
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - name: textlintの実行
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          textlint_flags: "*.md"

  # Alex
  # https://github.com/reviewdog/action-alex
  alex_CI:
    name: alex
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: alexによる査読
        uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          alex_flags: "*.md"