name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Redpen
  document_Redpen_CI:
    runs-on: ubuntu-latest
    env:
      redpen_conf: docs/config/Redpen-config.xml
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Redpenを実行:PRチェック
        uses: tsuyoshicho/action-redpen@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          targets: "*"
          config: ${redpen_conf}
      - name: Redpenを実行:チェック
        uses: tsuyoshicho/action-redpen@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          targets: "*"
          config: ${redpen_conf}
      - name: Redpenを実行:レビュー
        uses: tsuyoshicho/action-redpen@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          targets: "*"
          config: ${redpen_conf}

  # Textlint
  document_textlint_CI:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: nodejsの設定
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - name: textlintの実行:PRチェック
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: info
          textlint_flags: "*"
      - name: textlintの実行:チェック
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          textlint_flags: "*"
      - name: textlintの実行:レビュー
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info
          textlint_flags: "*"
